name: Chess Stats Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am IST
    - cron: "20 18 * * *"
jobs:
  update-readme:
    name: Update readme with chess stats
    runs-on: ubuntu-latest
    steps:
      - uses: IslamovMukhammad/chess-stats-readme@master
        with:
          CHESS_USERNAME: IslamovMuhammad
