name: Update chess data on README.md

on:
  schedule:
    - cron: '10 0 * * *'
  workflow_dispatch:
  
jobs:
  chess:
    name: Update chess.com stats and games
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: IslamovMuhammad/chess-stats-action@main
        with:
          CHESS_USERNAME: 'IslamovMuhammad'
